### ISSUE TITLE
Add docker image

### ISSUE THREAD

**Issue by jkone27** [JasonRowe/KestrelMock#15]
add docker image to run the mock component as standalone

**Comment by JasonRowe** [comment]
Would you need more then just a docker file or should we publish the image to a repo for use?

**Comment by jkone27** [comment]
i think a docker file should be good, and then we could publish it to docker public registry for other people (also non C# devs) to use in their project:

https://docs.docker.com/engine/examples/dotnetcore/

i am not expert in Docker tho : )

https://docs.docker.com/docker-hub/publish/publish/

**Comment by JasonRowe** [comment]
Good idea on using the TestMockServerWeb for this. I'll check to see how painful it is to use a volume or mount for the appsetting.json file when running a container. Hopefully it is not that bad and then we could just provide instructions. I could see this driving another API to add endpoints via HTTP instead of a configuration file.

**Comment by jkone27** [comment]
on the new in-memory API yes, that could be useful, you mean for in-memory mocking, if i got your suggestion correctly. the only issue could be that when it's containerized, restart might "clear" out memory  removing all in-memory stubs
